provider:
  volcengine-plan:
    name: "Volcano Engine"
    options:
      baseUrl: https://ark.cn-beijing.volces.com/api/coding/v3
      apiKey: "6e4b3036-60db-44b1-b3b2-dc081ddbcb3f"
    models:
      deepseek-v4-flash:
        name: "DeepSeek V4 Flash"
        limit:
          context: 1000000
          output: 384000
      deepseek-v4-pro:
        name: "DeepSeek V4 Pro"
        limit:
          context: 1000000
          output: 384000
      minimax-latest:
        name: "MiniMax Latest"
        limit:
          context: 200000
          output: 4096
      kimi-k2.6:
        name: "Kimi K2.6"
        limit:
          context: 256000
          output: 4096